var tree = [["Cryptography","Cryptography.html","",
                [["SubstitutionCipher","Cryptography\/SubstitutionCipher.html","",
                [["AbstractSubstitutionCipher","Cryptography\/SubstitutionCipher\/AbstractSubstitutionCipher.html","",
                [        ]],["AffineSubstitution","Cryptography\/SubstitutionCipher\/AffineSubstitution.html"," < SimpleSubstitution",
                [        ]],["HomophonicSubstitution","Cryptography\/SubstitutionCipher\/HomophonicSubstitution.html"," < SimpleSubstitution",
                [        ]],["Inversion","Cryptography\/SubstitutionCipher\/Inversion.html"," < SimpleSubstitution",
                [        ]],["PolyAlphabeticSubstitution","Cryptography\/SubstitutionCipher\/PolyAlphabeticSubstitution.html"," < SimpleSubstitution",
                [        ]],["RepertorySubstitution","Cryptography\/SubstitutionCipher\/RepertorySubstitution.html"," < HomophonicSubstitution",
                [        ]],["Rotation","Cryptography\/SubstitutionCipher\/Rotation.html"," < SimpleSubstitution",
                [        ]],["SimpleSubstitution","Cryptography\/SubstitutionCipher\/SimpleSubstitution.html"," < AbstractSubstitutionCipher",
                [        ]],["SquareSubstitution","Cryptography\/SubstitutionCipher\/SquareSubstitution.html"," < SimpleSubstitution",
                [        ]],["VigenereCipher","Cryptography\/SubstitutionCipher\/VigenereCipher.html"," < PolyAlphabeticSubstitution",
                [        ]]        ]],["SubstitutionTable","Cryptography\/SubstitutionTable.html","",
                [["AbstractSubstitutionTable","Cryptography\/SubstitutionTable\/AbstractSubstitutionTable.html","",
                [        ]],["ClosureSubstitutionTable","Cryptography\/SubstitutionTable\/ClosureSubstitutionTable.html"," < AbstractSubstitutionTable",
                [        ]],["RotarySubstitutionTable","Cryptography\/SubstitutionTable\/RotarySubstitutionTable.html"," < SimpleSubstitutionTable",
                [        ]],["SimpleSubstitutionTable","Cryptography\/SubstitutionTable\/SimpleSubstitutionTable.html"," < AbstractSubstitutionTable",
                [        ]],["SquareSubstitutionTable","Cryptography\/SubstitutionTable\/SquareSubstitutionTable.html"," < SimpleSubstitutionTable",
                [        ]],["TabulaRecta","Cryptography\/SubstitutionTable\/TabulaRecta.html","",
                [        ]]        ]],["Cryptography","Cryptography\/Cryptography.html","",
                [        ]],["Helper","Cryptography\/Helper.html","",
                [        ]]        ]]        ]

